// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: RayVision.proto
#ifndef GRPC_RayVision_2eproto__INCLUDED
#define GRPC_RayVision_2eproto__INCLUDED

#include "RayVision.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace rayvisiongrpc {

class RayVisionGrpc final {
 public:
  static constexpr char const* service_full_name() {
    return "rayvisiongrpc.RayVisionGrpc";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetImage(::grpc::ClientContext* context, const ::rayvisiongrpc::GetImageRequest& request, ::rayvisiongrpc::ImageData* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rayvisiongrpc::ImageData>> AsyncGetImage(::grpc::ClientContext* context, const ::rayvisiongrpc::GetImageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rayvisiongrpc::ImageData>>(AsyncGetImageRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rayvisiongrpc::ImageData>> PrepareAsyncGetImage(::grpc::ClientContext* context, const ::rayvisiongrpc::GetImageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rayvisiongrpc::ImageData>>(PrepareAsyncGetImageRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderInterface< ::rayvisiongrpc::SegmentationResult>> doSegmentation(::grpc::ClientContext* context, const ::rayvisiongrpc::Empty& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::rayvisiongrpc::SegmentationResult>>(doSegmentationRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::rayvisiongrpc::SegmentationResult>> AsyncdoSegmentation(::grpc::ClientContext* context, const ::rayvisiongrpc::Empty& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::rayvisiongrpc::SegmentationResult>>(AsyncdoSegmentationRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::rayvisiongrpc::SegmentationResult>> PrepareAsyncdoSegmentation(::grpc::ClientContext* context, const ::rayvisiongrpc::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::rayvisiongrpc::SegmentationResult>>(PrepareAsyncdoSegmentationRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetImage(::grpc::ClientContext* context, const ::rayvisiongrpc::GetImageRequest* request, ::rayvisiongrpc::ImageData* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetImage(::grpc::ClientContext* context, const ::rayvisiongrpc::GetImageRequest* request, ::rayvisiongrpc::ImageData* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void doSegmentation(::grpc::ClientContext* context, const ::rayvisiongrpc::Empty* request, ::grpc::ClientReadReactor< ::rayvisiongrpc::SegmentationResult>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rayvisiongrpc::ImageData>* AsyncGetImageRaw(::grpc::ClientContext* context, const ::rayvisiongrpc::GetImageRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rayvisiongrpc::ImageData>* PrepareAsyncGetImageRaw(::grpc::ClientContext* context, const ::rayvisiongrpc::GetImageRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderInterface< ::rayvisiongrpc::SegmentationResult>* doSegmentationRaw(::grpc::ClientContext* context, const ::rayvisiongrpc::Empty& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::rayvisiongrpc::SegmentationResult>* AsyncdoSegmentationRaw(::grpc::ClientContext* context, const ::rayvisiongrpc::Empty& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::rayvisiongrpc::SegmentationResult>* PrepareAsyncdoSegmentationRaw(::grpc::ClientContext* context, const ::rayvisiongrpc::Empty& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetImage(::grpc::ClientContext* context, const ::rayvisiongrpc::GetImageRequest& request, ::rayvisiongrpc::ImageData* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rayvisiongrpc::ImageData>> AsyncGetImage(::grpc::ClientContext* context, const ::rayvisiongrpc::GetImageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rayvisiongrpc::ImageData>>(AsyncGetImageRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rayvisiongrpc::ImageData>> PrepareAsyncGetImage(::grpc::ClientContext* context, const ::rayvisiongrpc::GetImageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rayvisiongrpc::ImageData>>(PrepareAsyncGetImageRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReader< ::rayvisiongrpc::SegmentationResult>> doSegmentation(::grpc::ClientContext* context, const ::rayvisiongrpc::Empty& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::rayvisiongrpc::SegmentationResult>>(doSegmentationRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::rayvisiongrpc::SegmentationResult>> AsyncdoSegmentation(::grpc::ClientContext* context, const ::rayvisiongrpc::Empty& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::rayvisiongrpc::SegmentationResult>>(AsyncdoSegmentationRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::rayvisiongrpc::SegmentationResult>> PrepareAsyncdoSegmentation(::grpc::ClientContext* context, const ::rayvisiongrpc::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::rayvisiongrpc::SegmentationResult>>(PrepareAsyncdoSegmentationRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetImage(::grpc::ClientContext* context, const ::rayvisiongrpc::GetImageRequest* request, ::rayvisiongrpc::ImageData* response, std::function<void(::grpc::Status)>) override;
      void GetImage(::grpc::ClientContext* context, const ::rayvisiongrpc::GetImageRequest* request, ::rayvisiongrpc::ImageData* response, ::grpc::ClientUnaryReactor* reactor) override;
      void doSegmentation(::grpc::ClientContext* context, const ::rayvisiongrpc::Empty* request, ::grpc::ClientReadReactor< ::rayvisiongrpc::SegmentationResult>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::rayvisiongrpc::ImageData>* AsyncGetImageRaw(::grpc::ClientContext* context, const ::rayvisiongrpc::GetImageRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::rayvisiongrpc::ImageData>* PrepareAsyncGetImageRaw(::grpc::ClientContext* context, const ::rayvisiongrpc::GetImageRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReader< ::rayvisiongrpc::SegmentationResult>* doSegmentationRaw(::grpc::ClientContext* context, const ::rayvisiongrpc::Empty& request) override;
    ::grpc::ClientAsyncReader< ::rayvisiongrpc::SegmentationResult>* AsyncdoSegmentationRaw(::grpc::ClientContext* context, const ::rayvisiongrpc::Empty& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::rayvisiongrpc::SegmentationResult>* PrepareAsyncdoSegmentationRaw(::grpc::ClientContext* context, const ::rayvisiongrpc::Empty& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetImage_;
    const ::grpc::internal::RpcMethod rpcmethod_doSegmentation_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetImage(::grpc::ServerContext* context, const ::rayvisiongrpc::GetImageRequest* request, ::rayvisiongrpc::ImageData* response);
    virtual ::grpc::Status doSegmentation(::grpc::ServerContext* context, const ::rayvisiongrpc::Empty* request, ::grpc::ServerWriter< ::rayvisiongrpc::SegmentationResult>* writer);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetImage() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetImage(::grpc::ServerContext* /*context*/, const ::rayvisiongrpc::GetImageRequest* /*request*/, ::rayvisiongrpc::ImageData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetImage(::grpc::ServerContext* context, ::rayvisiongrpc::GetImageRequest* request, ::grpc::ServerAsyncResponseWriter< ::rayvisiongrpc::ImageData>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_doSegmentation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_doSegmentation() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_doSegmentation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status doSegmentation(::grpc::ServerContext* /*context*/, const ::rayvisiongrpc::Empty* /*request*/, ::grpc::ServerWriter< ::rayvisiongrpc::SegmentationResult>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestdoSegmentation(::grpc::ServerContext* context, ::rayvisiongrpc::Empty* request, ::grpc::ServerAsyncWriter< ::rayvisiongrpc::SegmentationResult>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(1, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetImage<WithAsyncMethod_doSegmentation<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetImage() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::rayvisiongrpc::GetImageRequest, ::rayvisiongrpc::ImageData>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::rayvisiongrpc::GetImageRequest* request, ::rayvisiongrpc::ImageData* response) { return this->GetImage(context, request, response); }));}
    void SetMessageAllocatorFor_GetImage(
        ::grpc::MessageAllocator< ::rayvisiongrpc::GetImageRequest, ::rayvisiongrpc::ImageData>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::rayvisiongrpc::GetImageRequest, ::rayvisiongrpc::ImageData>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetImage(::grpc::ServerContext* /*context*/, const ::rayvisiongrpc::GetImageRequest* /*request*/, ::rayvisiongrpc::ImageData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetImage(
      ::grpc::CallbackServerContext* /*context*/, const ::rayvisiongrpc::GetImageRequest* /*request*/, ::rayvisiongrpc::ImageData* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_doSegmentation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_doSegmentation() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackServerStreamingHandler< ::rayvisiongrpc::Empty, ::rayvisiongrpc::SegmentationResult>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::rayvisiongrpc::Empty* request) { return this->doSegmentation(context, request); }));
    }
    ~WithCallbackMethod_doSegmentation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status doSegmentation(::grpc::ServerContext* /*context*/, const ::rayvisiongrpc::Empty* /*request*/, ::grpc::ServerWriter< ::rayvisiongrpc::SegmentationResult>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::rayvisiongrpc::SegmentationResult>* doSegmentation(
      ::grpc::CallbackServerContext* /*context*/, const ::rayvisiongrpc::Empty* /*request*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetImage<WithCallbackMethod_doSegmentation<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetImage() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetImage(::grpc::ServerContext* /*context*/, const ::rayvisiongrpc::GetImageRequest* /*request*/, ::rayvisiongrpc::ImageData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_doSegmentation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_doSegmentation() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_doSegmentation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status doSegmentation(::grpc::ServerContext* /*context*/, const ::rayvisiongrpc::Empty* /*request*/, ::grpc::ServerWriter< ::rayvisiongrpc::SegmentationResult>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetImage() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetImage(::grpc::ServerContext* /*context*/, const ::rayvisiongrpc::GetImageRequest* /*request*/, ::rayvisiongrpc::ImageData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetImage(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_doSegmentation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_doSegmentation() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_doSegmentation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status doSegmentation(::grpc::ServerContext* /*context*/, const ::rayvisiongrpc::Empty* /*request*/, ::grpc::ServerWriter< ::rayvisiongrpc::SegmentationResult>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestdoSegmentation(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(1, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetImage() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetImage(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetImage(::grpc::ServerContext* /*context*/, const ::rayvisiongrpc::GetImageRequest* /*request*/, ::rayvisiongrpc::ImageData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetImage(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_doSegmentation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_doSegmentation() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->doSegmentation(context, request); }));
    }
    ~WithRawCallbackMethod_doSegmentation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status doSegmentation(::grpc::ServerContext* /*context*/, const ::rayvisiongrpc::Empty* /*request*/, ::grpc::ServerWriter< ::rayvisiongrpc::SegmentationResult>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* doSegmentation(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetImage() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::rayvisiongrpc::GetImageRequest, ::rayvisiongrpc::ImageData>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::rayvisiongrpc::GetImageRequest, ::rayvisiongrpc::ImageData>* streamer) {
                       return this->StreamedGetImage(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetImage(::grpc::ServerContext* /*context*/, const ::rayvisiongrpc::GetImageRequest* /*request*/, ::rayvisiongrpc::ImageData* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetImage(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::rayvisiongrpc::GetImageRequest,::rayvisiongrpc::ImageData>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetImage<Service > StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_doSegmentation : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_doSegmentation() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::rayvisiongrpc::Empty, ::rayvisiongrpc::SegmentationResult>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::rayvisiongrpc::Empty, ::rayvisiongrpc::SegmentationResult>* streamer) {
                       return this->StreameddoSegmentation(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_doSegmentation() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status doSegmentation(::grpc::ServerContext* /*context*/, const ::rayvisiongrpc::Empty* /*request*/, ::grpc::ServerWriter< ::rayvisiongrpc::SegmentationResult>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreameddoSegmentation(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::rayvisiongrpc::Empty,::rayvisiongrpc::SegmentationResult>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_doSegmentation<Service > SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetImage<WithSplitStreamingMethod_doSegmentation<Service > > StreamedService;
};

}  // namespace rayvisiongrpc


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_RayVision_2eproto__INCLUDED
